### ISSUE TITLE
Authentication: Add support for non-user profiles

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Server#1401]
## Description
As an admin I want to have specific accounts for specific services.
As a user I do not care about service accounts and so I do not want to see them. 

## Acceptance criteria

- [ ] Service Profile should be able to work with the existing authentication and authorization framework
- [ ] They should not be returned for queries that return users e.g. top level users() query. 
- [ ] Service Profile should not be counted in activity metrics
