### ISSUE TITLE
Platform Templates via TemplateProviders

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1963]
As a service manager I want to be able to offer platform wide templates so that best practices  + knowledge can be shared

## Acceptance criteria
- [ ] Ability to manage templates at platform level, including the following types: AspectTemplates, CanvasTemplates, LifecycleTemplates
- [ ] Multiple  Template providers, each providing templates of various types
- [ ] Provide a set of default templates that are assigned to all Hubs on instantiation, removing the hard coded list of templates currently in the code base
- [ ] Ability to manage the Platform level Template Providers and the included templates for global admins

## Additional Information

- Hub admin to bring best practices into a hub from the store
