### ISSUE TITLE
ORM Mapping Layer optimisation

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#1972]
## Description
As a developer I want a clean ORM mapping layer to be effective
As a user I want a performant application

## Initiative / goal
Maintainability
Performance

### Hypothesis
Updating the version of TypeORM means we are up to date if bugs arise

## Acceptance criteria and must have scope
- [ ] Upgrade to TypeORM 0.3.11
- [ ] Evaluation of new capabilities in TypeORM and what the benefits could be for Alkemio
- [ ] Evaluation of the migration generation capabilities + what is needed to get current setup working with generated migrations again

## Stakeholders
development

## Timeline
tbd

## Additional Context
There is a neat utility method findBy - check its usage
