### ISSUE TITLE
Activity tracking prototype

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2133]
## Description
As a user I want to be able to see activity on the platform
As an admin I want to see what has happened within my entity

## Acceptance criteria
- [ ] Activity entity to record an event
- [ ] Activity adapter service to handle the publishing of activity events
- [ ] Activity query service to allow reading of activity records

**Comment by Comoque1** [comment]
Tested on DEV env.

Raised the following bugs:
 - BUG: Member_joined event is not returned from activity log query #2159
 - BUG: Querying activity logs on challenge / opportunity collaboration, throws an error#2158
