### ISSUE TITLE
Server: api, auth + code

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2189]
## Description
Keeping the server provided api and code structure clean, including how authorization policies cascade

## Initiative / goal
Maintainability

### Hypothesis
By having a clean api, understandable code structure and clean authorization policies setup the maintenance load on the server is less

## Acceptance criteria and must have scope
- [ ] Authorization policies cleaned up to address cases where too many privileges are cascaded
- [ ] services area refactored
- [ ] activity ==> metrics in the api
- [ ] users are associated of organizations

## Stakeholders
Development

## Timeline
tbd
