### ISSUE TITLE
Domain Model: Profiles

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#2421]
## Description
Ensuring that the server domain model is clean and can support expanding usage

## Initiative / goal
Maintainability

### Hypothesis
Addressing the domain model gaps / known issues allows for the domain model base to continue to grow effectively

## Acceptance criteria and must have scope
- [ ] Profile entity expanded with: tagline, nameID, displayName, description, visuals
- [ ] User/Organization entity updated to use the nameID, displayName from the Profile entity
- [ ] CardProfile entity replaced by usage of Profile entity
- [ ] Profile added to Hub / Challenge / Opportunity, with data migrated: nameID, displayName, tagline, tagset, description (background?), references migrated to be the data on Profile
- [ ] Profile added to Canvas / Callout, replacing nameID, displayName 

To update:
- Test Suites
- Populator
- CLI

tbd: extend Profile entity to have a field for getting the visual URI directly e.g. visualUri("avatar")? also to have a list per Profile of allowed visual types?
tbd: also use Profile on templates?

## Stakeholders
Developers

## Timeline
tbd
