### ISSUE TITLE
Alkemio for 10,000 users

### ISSUE THREAD

**Issue by Comoque1** [cherrytwist/Server#2585]
## Description
Assure Alkemio performance for 10 000 users

## Initiative / goal
Usage
- [ ] Alkemio can handle usage as follows on different user load with respect to different types of events
   - [ ]  Normal Usage: 1k, 5k users
   - [ ] Hackathon: TBD
   - [ ] Extreme usage: TBD (10k users)

### Hypothesis
By having split the load on Alkemio system by different types of events, we can evaluate the types of performance testing to be applied, the existing gaps, the areas to be improved and the scalability options.

## Acceptance criteria and must have scope
- [ ] Model user behavior
- [ ] Benchmark / Monitoring of systems
- [ ] Results analyzes 
- [ ] Planning and prioritization of analyzes results
- [ ] Address the the prioritized items (potentially split in different epic)
- [ ] Ensure different service scalability

## Stakeholders
Investors
Sales

## Technical notes
[Discussions](https://stichtingcherrytwist.sharepoint.com/sites/Contributors) performed so far.
