### ISSUE TITLE
Add tracking of activity in whiteboard RT

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#3410]
## Description

As an admin I want to be able to show activity on whiteboard rt

## Acceptance criteria

- [ ] If a user is contributing to a whiteboard, e.g. text / circle (and excluding presencing, scrolling etc) then if the user has not contributed in the last 10 minutes then trigger the registration of a new contribution
- [ ] Time window of 10 minutes to be configurable by the server
- [ ] Contribution to be sent to the Elastic

## Additional Context

Screen shots / UX designs / data that are relevant.
