### ISSUE TITLE
Meta information on data sources

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Server#4185]
## Description

As a user I want to be able to have transparency from the AI persona on how my data is generated

## Acceptance criteria

- [ ] Server to be able to receive and process additional meta information on data sources
- [ ] MessageAnswerToQuestion extended to make this available
- [ ] Content of normal Messages to give access to this meta data (design tbd)

## Additional Context

Screen shots / UX designs / data that are relevant.

## Areas that will be affected 
 
_To be added during the refinement_
